const DEFAULT_PORT = 8500;
const DEFAULT_HOST = 'http://localhost';
const DEFAULT_WAIT_TIME_IN_MINUTE = '30m';
const DEFAULT_BACKOFF_FAIL_AFTER = 10;
const DEFAULT_QUISCENCE_PERIOD_IN_MS = 500;
const DEFAULT_QUISCENCE_TIMEOUT_IN_MS = 5;

module.exports = {
  DEFAULT_PORT,
  DEFAULT_HOST,
  DEFAULT_WAIT_TIME_IN_MINUTE,
  DEFAULT_BACKOFF_FAIL_AFTER,
  DEFAULT_QUISCENCE_PERIOD_IN_MS,
  DEFAULT_QUISCENCE_TIMEOUT_IN_MS
};
